name: Deploy to Hugging Face Spaces

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        run: |
          git remote add space https://huggingface.co/spaces/Programmer-RD-AI/mcp-carbon-calculator
          git push space main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
