name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install Ruff globally
        run: uv tool install ruff

      - name: Install dependencies
        run: make install

      - name: Run clean
        run: make clean

      - name: Run lint
        run: make lint

      - name: Run format
        run: make format
